#!/bin/bash
set -eu -o pipefail

########################################################
## sampleOutdir is passed in via an sbatch export
########################################################

echo In prep_bamintersect.sh

# These files were created by the two sort_bamintersect array jobs.
ls -1 ${sampleOutdir}/bams/*.1.bam > "${sampleOutdir}/bams/chr_list_1"
ls -1 ${sampleOutdir}/bams/*.2.bam > "${sampleOutdir}/bams/chr_list_2"

TEMP_DIR_CL1="${sampleOutdir}/TEMP_DIR_CL1"
echo TEMP_DIR_CL1 is: ${TEMP_DIR_CL1}
mkdir ${TEMP_DIR_CL1}

## bam1 is a full path to the sorted, single chromosome bam file generated by sort_chrom.sbatch
## BASE1 looks like this (for each chromosome):         chr10.1.bam
## bam2 and BASE2 are similar.  BASE2 looks like this:  chr10_KL568015v1_random.2.bam
while read -r bam1; do
    while read -r bam2; do
        BASE1=${bam1##*/}    ## Get rid of the path before the bam file name.
        BASE2=${bam2##*/} 

        BASE1=${BASE1#*\.}   ## Get rid of the sample name.
        BASE2=${BASE2#*\.} 

        echo ${bam1} ${bam2} "${TEMP_DIR_CL1}/${BASE1}___${BASE2}"  >> "${sampleOutdir}/bams/array_list"
    done < "${sampleOutdir}/bams/chr_list_2"
done < "${sampleOutdir}/bams/chr_list_1"

echo Leaving prep_intersect.sh

